### ISSUE TITLE
Further expansion of test routines

### ISSUE THREAD

**Issue by GoogleCodeExporter** [globalcitizen/php-iban#15]
```
Issues observed include:
 * Lack of an extended test library (input/output expectations)
 * Lack of environment testing (eg. PHP gmp extension present/missing)
 * No way to test subcomponents (such as differing MOD97 routines)
 * No xdebug-style code coverage analysis for test library
```

Original issue reported on code.google.com by `walter.stanish@gmail.com` on 16 Feb 2013 at 1:12

**Comment by globalcitizen** [comment]
There is further work to do here but at least now we have Travis CI running and the test script actually executes every time a commit is made. So there's been a lot of improvement. Leaving this open until the original points are all knocked off.

**Comment by globalcitizen** [comment]
I'm going to call these closed at present, since arbitrary function input/ouput expectations are now in `utils/other-tests.php`, failing a test is not appropriate or useful for `gmp` extension detection since we can work with or without it, subcomponents may be tested similarly to established test routines (just need to write some more tests!). I will make a new issue for code coverage analysis.
