### ISSUE TITLE
Make it a composer library

### ISSUE THREAD

**Issue by GoogleCodeExporter** [globalcitizen/php-iban#30]
```
Have you think in release php-iban library as a Composer package?

It will make to other add your library to its projects without effort.

It is very easy to make it composer compatible, as simply as adding a json file 
(with little configuration) and submiting an entry to packagist.

You can read more about composer in http://getcomposer.org
```

Original issue reported on code.google.com by `PhoneixS...@gmail.com` on 14 Aug 2014 at 11:13

**Comment by globalcitizen** [comment]
Done, finally.

**Comment by acoulton** [comment]
@globalcitizen will you be adding the package to packagist? It's relatively straightforward:

* [Login to packagist - you can use github oauth](https://packagist.org/login/)
* [Submit the package](https://packagist.org/packages/submit)

Ideally you'd also set up a github hook so packagist gets triggered to update the list of available versions whenever you push/tag a release (otherwise it crawls occasionally). You can follow the docs, or these two links should get you to the pages you need:
* [Go to your packagist profile and copy your API token](https://packagist.org/profile/)
* [Add the packagist service to this repo's settings](https://github.com/globalcitizen/php-iban/settings/hooks/new?service=packagist)

That should be the last time you have to touch packagist, it's basically invisible after that.

Then anyone can add the library to their project by just running `composer require globalcitizen/php-iban`

**Comment by globalcitizen** [comment]
OK, I think that's all done.

**Comment by acoulton** [comment]
@globalcitizen great, thanks!
