### ISSUE TITLE
Do you plan on doing releases?

### ISSUE THREAD

**Issue by rodrigoaguilera** [globalcitizen/php-iban#33]
In the old SVN structure there was tags.

**Comment by globalcitizen** [comment]
Why do you ask? (How) would that be useful for you? What kind of automated method would you  recommend? I'm willing to do anything users wish, I'm just also interested in reducing the need for manual process since I am often in China where connectivity is crap and uploads are like slowly slitting your wrists while dining on raw chilli in a bath of vinegar listening to noise music.

**Comment by rodrigoaguilera** [comment]
I suggest just using github tags https://github.com/globalcitizen/php-iban/releases.

The problem arises from my build scripts downloading the master branch instead of a releases. Since the code that I was using changed 2 days ago in this repo I had to change to
https://github.com/{username}/{projectname}/archive/{sha}.zip

With a release it can be easier.

Have fun in China :)

**Comment by globalcitizen** [comment]
OK, I'll leave this open and make a mental note to sort it out ASAP. Maybe tomorrow. Sorry for the trouble caused, I had no idea people were writing build scripts based on the repo!

**Comment by rodrigoaguilera** [comment]
My bad for not pinpointing to a commit.
Feels cleaner to pinpoint to a release

**Comment by globalcitizen** [comment]
https://github.com/globalcitizen/php-iban/releases/tag/v1.4.9

**Comment by rodrigoaguilera** [comment]
Thanks!

**Comment by acoulton** [comment]
@globalcitizen thanks!
