### ISSUE TITLE
branch name is empty

### ISSUE THREAD

**Issue by flik** [globalcitizen/php-iban#54]
branch name not coming and  also account number is coming with 0000 which is wrong.

**Comment by globalcitizen** [comment]
You cannot obtain this information for all countries, because not all countries had a pre-IBAN national system with a fixed length and location for the branch identifier for all banks.

It is possible that there are countries where such a system did exist but we do not know about it.

Could you please tell me which country's IBAN you were testing on?

**Comment by flik** [comment]
well. thanks for help
