### ISSUE TITLE
IBAN Validation incorrect for number zero instead of letter 'O'

### ISSUE THREAD

**Issue by mclambert** [globalcitizen/php-iban#63]
When my IBAN parameter is equal to "FR742004101012512346OUO3388" or "FR7420041010125123460U03388", the validation is ok. 

It shouldn't be. As one of the IBAN is wrong because we entered letter "O" instead of number "0".

**Comment by globalcitizen** [comment]
Interesting bug report. Are you sure that both are invalid?

I wrote the following test code.

```
<?php

require_once('php-iban.php');

$ibans = array('FR742004101012512346OUO3388','FR7420041010125123460U03388');

foreach($ibans as $iban) {
        if(!verify_iban($iban)) {
                print "$iban was invalid.\n";
        }
        else {
                print "$iban was valid.\n";
        }
}
?>
```

The output was as per the report.
```
FR742004101012512346OUO3388 was valid.
FR7420041010125123460U03388 was valid.
```

Unfortunately I do not have time right now to get in to the guts of the checksum algorithm implementation, which has never had a false report of validity in many years of use by many, many people. Would you be willing to find any alternate implementations with differing results and list them here as additional evidence of improper results? This would make it easier to justify the time. I slightly suspect there is a chance that this is a limitation of the checksum algorithm rather than an actual issue.

**Comment by mclambert** [comment]
Hi,

First of all, thanks for your quick answer. 

This one (with the number '0')  is supposed to be valid : **FR7420041010125123460U03388**

![validiban](https://user-images.githubusercontent.com/4490538/29860851-b13fea96-8d67-11e7-9424-3aa34e20ed8a.jpg)

This one (with the letter 'O') is supposed to be invalid : **FR742004101012512346OUO3388**

![invalidiban](https://user-images.githubusercontent.com/4490538/29860844-ae1ae0f0-8d67-11e7-9b5f-153de8f3915e.jpg)

The problem is that, as you showed me with your implementation, both are valid. 

When I have time, I will investigate in alternate implementations, I will come back to you. 
I think it's a limitation in the checksum algorithm too. 

Again, thanks for your quick answer, and congratulations for your work.

**Comment by globalcitizen** [comment]
Thanks for your detailed response. I think another one or two implementations would be very handy just to make sure the bug is ours and not theirs. If you can find the time to do it, this would be great.

I guess that there may be some issues with '0' being interpreted incorrectly through PHP's soft type system.

Actually, I could even put some alternate implementations in to the automated test suite just to re-validate our implementation further in future... though this is not high priority right now and would be a pretty big time sink.

**Comment by mclambert** [comment]
Hi! Thanks again for your answer. 

If I have time to do it, I will make more tests and put them here 

No problem for your priorities, good luck with your work.

**Comment by globalcitizen** [comment]
I am still keen to get to the bottom of this. It will happen eventually. Any help appreciated 👍

**Comment by globalcitizen** [comment]
```
IBAN FR7420041010125123460U03388 is valid.
Array
(
    [checksum] => 74
    [bban] => 20041010125123460U03388
    [bank] => 20041
    [country] => FR
    [branch] => 01012
    [account] => 5123460U03388
    [nationalchecksum] => 88
)
 - national checksum valid.
IBAN FR742004101012512346OUO3388 is valid.
Array
(
    [checksum] => 74
    [bban] => 2004101012512346OUO3388
    [bank] => 20041
    [country] => FR
    [branch] => 01012
    [account] => 512346OUO3388
    [nationalchecksum] => 88
)
 - national checksum invalid.
```

Generated from the following code...
```
#!/usr/bin/php
<?php

require_once('php-iban.php');

$ibans = array(
		'FR7420041010125123460U03388',
		'FR742004101012512346OUO3388'
	 );

foreach($ibans as $iban) {
	print "IBAN $iban is ";
	if(!verify_iban($iban)) {
	 print "in";
	}
	print "valid.\n";
	$parts = iban_get_parts($iban);
	print_r($parts);
	if(!iban_verify_nationalchecksum($iban)) {
		print " - national checksum invalid.\n";
	}
	else {
		print " - national checksum valid.\n";
	}
}

?>
```

What this means is that the IBAN is valid, only the national checksum is invalid. This is correctly checked as being invalid. We don't test for that unless it is done explicitly, since it is not part of the IBAN standard.

This is presumably why the IBAN in question is marked invalid by another site, but valid by us... because from the perspective of the IBAN standard, it is. Many nations with legacy national checksum schemes do not publish them or are in the process of relaxing or removing them, so from a global perspective it is not wise to rely on them. If you want to rely on them, for countries we have an implementation for, you can do so explicitly.
