### ISSUE TITLE
Do not preload Iban registry to memory

### ISSUE THREAD

**Issue by mikk150** [globalcitizen/php-iban#80]
https://github.com/globalcitizen/php-iban/blob/master/php-iban.php#L474 load iban registry into memory wasing 1.6ms of CPU time even if I am not using this library in this action..

you can say that 1.6ms is nothing, but in fact it is 10% of total request time which is HUGE for library that is not always needed

**Comment by globalcitizen** [comment]
Maybe don't load it unless needed? That would be smarter.

**Comment by globalcitizen** [comment]
PS. To achieve that, use PHP's built-in `include_once()` or `require_once()` directives. They make it very easy to include source only when required. Although, in this era of fifteen levels of object oriented package management indirection, the above may sound like black magic, I assure you it works fine.

**Comment by mikk150** [comment]
Unfortunately this is not going to work if you use autoloader, where you have exclusively told to pre-load those files which automatically ofcource loads them in, so no include_once or require_once, since they are already loaded...

**Comment by globalcitizen** [comment]
If you actually looked at the file you linked to, I didn't write it, it was contributed by someone else. That is because I don't use composer, or object oriented PHP in general.

[This line however](https://github.com/globalcitizen/taoup/blob/master/taoup#L139) is attributed to me, but only as I was amused enough by someone else's words to record them for future amusement. Perhaps they apply here?
