### ISSUE TITLE
Composer autoloader config

### ISSUE THREAD

**Issue by SamMousa** [globalcitizen/php-iban#89]
This package uses the composer autoloader in a suboptimal way.

Instead of using the `files` key for listing both files, it should be enough to have the functional version in there.

The OO version can be autoloaded via a generated classmap:
https://getcomposer.org/doc/04-schema.md#classmap

**Comment by globalcitizen** [comment]
https://github.com/globalcitizen/taoup/blob/master/taoup#L226

**Comment by SamMousa** [comment]
My bad, I thought you were part of the audience that included people who want to improve their code and their skills. Won't bother you again.

**Comment by kfb-ts** [comment]
Hi there

While there's probably no issue regarding performance, the pollution of the global namespace is an issue (mostly) in bigger projects.
If all functions were prefixed with _iban that'd be less of a problem, though still annoying. But functions like `_italian()` are, for one, unclear in their behavior and might also easily lead to conflicts.

So I'm wondering whether you'd be open for improvements in that direction, even if they'd introduce breaking changes. I'd be happy to actually implement them.

These would some of the options for the procedural code:
- Add iban prefixes to all functions (besides verify_iban) and move global flags into the related functions, so they don't pollute until they're being used
- Get rid of the procedural code
- Remove the procedural code from autoloading

And for the OOP code:
- Use the composer classmap setting instead of the file autoloading. It's basically lazy autoloading for the class file and has almost no negative side effect, unless someone would be doing some weird things with the autoloader configuration
- Use a namespace and PSR4 (E.g. GlobalCitizen/PhpIban)
  - This would mean dropping support for PHP < 5.3, but composer itself doesn't support PHP < 5.3.2
  - An alternative would be to provide both, classes with namespaces for autoloading and classes without that aren't being autoloaded
